version: '3.8'

services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #    - '80:80'
  #    - '443:443'
  mongodb:
    image: mongo:4.2.5

  server:
    build: .
    ports:
      - '9091:9090'
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb_data:
