version: '3.8'

services:
  mongodb:
    image: mongo:4.2.5
    ports:
      - '27017:27017'

  server:
    build: .
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: mongodb:27017d
    depends_on:
      - mongodb

volumes:
  mongodb_data: