version: '3.8'

services:
  mongodb:
    image: mongo:4.2.5
  server:
    build: .
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - media_volume:/app/img

volumes:
  mongodb_data:
  media_volume: